"""change asossiation

Revision ID: 15560c16c597
Revises: bffdb87c4f7e
Create Date: 2022-09-09 00:13:04.727809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15560c16c597'
down_revision = 'bffdb87c4f7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_to_notes',
    sa.Column('notes_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], )
    )
    op.drop_table('tags_to_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_to_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notes_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], name='tags_to_notes_notes_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], name='tags_to_notes_tags_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='tags_to_notes_pkey')
    )
    op.drop_table('tag_to_notes')
    # ### end Alembic commands ###
