"""change Note

Revision ID: 302903715a87
Revises: a2bb15e65949
Create Date: 2022-09-06 11:38:51.741799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302903715a87'
down_revision = 'a2bb15e65949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
