"""change tag

Revision ID: 3a690de632b5
Revises: f9372dd260db
Create Date: 2022-09-06 15:47:14.045689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a690de632b5'
down_revision = 'f9372dd260db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_tag_key', 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tags_tag_key', 'tags', ['tag'])
    # ### end Alembic commands ###
