"""add clases Notes

Revision ID: 52eb45fd326d
Revises: f3dbf0a6dcce
Create Date: 2022-09-02 15:45:01.612442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52eb45fd326d'
down_revision = 'f3dbf0a6dcce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_to_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes_id', sa.Integer(), nullable=True),
    sa.Column('tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notes_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tags_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notes', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_column('notes', 'phone')
    op.drop_column('notes', 'birthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('birthday', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('phone', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('notes', 'created')
    op.drop_table('tags_to_notes')
    op.drop_table('records')
    op.drop_table('tags')
    # ### end Alembic commands ###
