"""change Note

Revision ID: 9de1f862db35
Revises: 915d1e020989
Create Date: 2022-09-06 15:17:08.684133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de1f862db35'
down_revision = '915d1e020989'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('transferred', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.add_column('tags', sa.Column('tag', sa.String(length=60), nullable=False))
    op.drop_constraint('tags_name_key', 'tags', type_='unique')
    op.create_unique_constraint(None, 'tags', ['tag'])
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_unique_constraint('tags_name_key', 'tags', ['name'])
    op.drop_column('tags', 'tag')
    op.drop_table('archives')
    # ### end Alembic commands ###
