"""change tag1

Revision ID: bffdb87c4f7e
Revises: 3a690de632b5
Create Date: 2022-09-06 15:51:49.836492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffdb87c4f7e'
down_revision = '3a690de632b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('archives_tag_key', 'archives', type_='unique')
    op.create_unique_constraint(None, 'tags', ['tag'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.create_unique_constraint('archives_tag_key', 'archives', ['tag'])
    # ### end Alembic commands ###
